# Generated by Django 2.2.2 on 2019-06-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AL_reletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '文章标签关系表',
            },
        ),
        migrations.CreateModel(
            name='Articals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=100, verbose_name='文章简介')),
                ('detail', models.TextField(max_length=1000, verbose_name='文章内容')),
                ('article_type_id', models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'OpenStack'), (4, 'GoLang')], default=None)),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(verbose_name='明星ID')),
                ('fans', models.IntegerField(verbose_name='粉丝ID')),
            ],
            options={
                'verbose_name_plural': '互粉',
            },
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '报障处理',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='处理者')),
                ('weight', models.IntegerField(verbose_name='权限级别')),
            ],
            options={
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, verbose_name='用户')),
                ('pwd', models.CharField(max_length=16, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=32, verbose_name='用户邮箱')),
                ('img', models.ImageField(upload_to='static/upload/users', verbose_name='用户头像')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default='Sat Jun 15 10:42:33 2019', verbose_name='提交时间')),
                ('title', models.CharField(max_length=32, verbose_name='报障标题')),
                ('detail', models.TextField(max_length=2000, verbose_name='详细描述')),
                ('status', models.NullBooleanField(default=0, verbose_name='处理状态')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Users', verbose_name='报障用户')),
                ('method', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='screen.Kill', verbose_name='解决方案')),
            ],
            options={
                'verbose_name_plural': '报障单',
            },
        ),
        migrations.AddField(
            model_name='kill',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Manager', verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='kill',
            name='method',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='screen.Trouble', verbose_name='解决方案'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('ctime', models.DateTimeField(default='Sat Jun 15 10:42:33 2019', verbose_name='评论时间')),
                ('Interaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screen.Comments', verbose_name='互动')),
                ('articls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Articals', verbose_name='评论的文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('surfix', models.CharField(max_length=32, verbose_name='blog后缀')),
                ('title', models.CharField(max_length=32, verbose_name='博客标题')),
                ('summary', models.TextField(max_length=120, verbose_name='博客简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screen.Users', verbose_name='博客主人')),
            ],
            options={
                'verbose_name_plural': '个人博客',
            },
        ),
        migrations.CreateModel(
            name='Articals_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16, verbose_name='类名')),
                ('Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Blog', verbose_name='博主')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Articals_lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16, verbose_name='标签')),
                ('Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Blog', verbose_name='博主')),
            ],
            options={
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='articals',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Blog', verbose_name='文章所属博客'),
        ),
        migrations.AddField(
            model_name='articals',
            name='lable',
            field=models.ManyToManyField(through='screen.AL_reletion', to='screen.Articals_lable'),
        ),
        migrations.AddField(
            model_name='articals',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Articals_sort', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='al_reletion',
            name='Aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Articals', verbose_name='文章ID'),
        ),
        migrations.AddField(
            model_name='al_reletion',
            name='Lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Articals_lable', verbose_name='标签ID'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.SmallIntegerField(choices=[(0, '赞'), (1, '踩')], verbose_name='赞与踩')),
                ('Aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Articals', verbose_name='文章ID')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Users', verbose_name='用户ID')),
            ],
            options={
                'verbose_name_plural': '赞踩表',
                'unique_together': {('Aid', 'Uid')},
            },
        ),
    ]
