# Generated by Django 2.2.2 on 2019-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articals',
            name='ctime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='ctime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间'),
        ),
    ]
