# Generated by Django 2.2.2 on 2019-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_auto_20190618_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/users', verbose_name='用户头像'),
        ),
    ]
