# Generated by Django 2.2.2 on 2019-06-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_auto_20190620_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screen.Comments', verbose_name='互动'),
        ),
    ]
