# Generated by Django 2.2.2 on 2019-06-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_auto_20190621_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='screen.Articals', verbose_name='评论的文章'),
        ),
    ]
